#!/bin/sh

# Environment
COMMAND=$1
SCRIPT=$0
OS=$(uname -s)
PLATFORM=$(uname -m)

# Options
QUIET=false
VERBOSE=0

# Output colors
COLOR_INFO='\033[0;32m'
COLOR_ERROR='\033[0;31m'
COLOR_WARN='\033[0;33m'
COLOR_NONE='\033[0m'

#
# Write to the console
#
console() {
    if [ $VERBOSE -ge "${3:-0}" ]; then
        case "$1" in
            warn)
                color=$COLOR_WARN;
                ;;
            error)
                color=$COLOR_ERROR;
                ;;
            info)
                color=$COLOR_INFO;
                ;;
            log)
                color=$COLOR_NONE;
                ;;
        esac

        echo "${color}${2}"
    fi
}

#
# Print a message and exit
#
die() {
  console error "$1" && exit ${2:-1}
}

#
# Execute a shell command
#
execute() {
    OUT=$("${@}" 2>&1)
    RC=$?

    if [ $QUIET = false ]; then
        console log "$OUT"
    fi
    
    exit $RC
}

#
# Print program help text
#
help() {
  help=$(cat << EOF
    Usage: $SCRIPT [-qv] COMMAND [ARGS...]
    available commands:
      rpc                 Execute a JSON-RPC command
      exec                Execute a shell command in a container
    optional arguments:
      -h, --help          Show this help message and exit
      -q, --quiet         Surpress all output
      -v, --verbose       Show verbose output
EOF
)

  console info "${help}\n" && exit 0
}

#
# Execute a command in the docker container
#
docker_exec() {
    execute docker exec "${@}"
}

#
# Send a JSON-RPC command to the bitcoin service
#
rpc() {
    docker_exec bitcoin bash -c "bitcoin-cli -conf=/etc/bitcoin.conf -datadir=/var/lib/bitcoind ${@}"
}

#
# Parse command options
#
case $1 in
  -q|--quiet)
    QUIET=true
    shift
    ;;
  -v|--verbose)
    VERBOSE=1
    shift
    ;;
esac

#
# Parse commands and arguments
#
case $1 in
    rpc)
        shift
        rpc "${@:---help}"
        ;;
    exec)
        CONTAINER=$2
        shift 2

        docker_exec $CONTAINER "${@}"
        ;;
    *|-h|--help)
        help
        ;;
esac

exit 0