version: '3.7'
services:

  bitcoin:
    container_name: bitcoin
    build:
      context: .docker/services/bitcoin
    volumes:
      - bitcoind_data:/var/lib/bitcoind
    ports:
     - 18444:18444
     - 18443:18443
    environment:
      BITCOIN_RPC_USERNAME: bitcoin
      BITCOIN_RPC_PASSWORD: bitcoin
      BITCOIN_TX_FALLBACK_FEE: '0.00001'

  esplora:
    container_name: esplora
    build:
      context: .docker/services/esplora
    volumes:
      - bitcoind_data:/var/lib/bitcoind:ro
      - electrum_data:/var/lib/electrs
    ports:
      - 80:80
    environment:
      BITCOIN_RPC_HOST: bitcoin
      BITCOIN_RPC_PORT: 18443

volumes:
  bitcoind_data:
  electrum_data: