version: '3.7'

services:

  bitcoin:
    container_name: bitcoin
    build: 
      target: bitcoin
      context: .docker/services/bitcoin
    volumes:
      - node_blockchain_data:/var/lib/bitcoind
    ports:
     - 18444:18444
     - 18443:18443

  peer:
    container_name: bitcoin-peer
    build: 
      target: bitcoin-peer
      context: .docker/services/bitcoin
    volumes:
      - peer_blockchain_data:/var/lib/bitcoind
    ports:
     - 18445:18444

  electrs:
    container_name: electrum-server
    build: 
      context: .docker/services/electrs
    volumes:
      - electrum_server_data:/var/lib/electrs
    ports:
      - 50001:50001
    depends_on:
      - bitcoin
    environment:
      ELECTRS_BITCOIN_HOSTNAME: bitcoin
      ELECTRS_BITCOIN_NETWORK: regtest
      ELECTRS_BITCOIN_P2P_PORT: 18444
      ELECTRS_BITCOIN_RPC_PORT: 18443
      ELECTRS_BITCOIN_RPC_USERNAME: root
      ELECTRS_BITCOIN_RPC_PASSWORD: password
      ELECTRS_ELECTRUM_HOST: 0.0.0.0
      ELECTRS_ELECTRUM_PORT: 50001

  mempool:
    container_name: mempool
    build: 
      context: .docker/services/mempool
    ports:
      - 3001:80
      - 3002:8999
    depends_on:
      - bitcoin
      - electrs
      - mariadb
    environment:
      MEMPOOL_NETWORK: regetest
      MEMPOOL_BACKEND: electrum
      MEMPOOL_INITIAL_BLOCKS_AMOUNT: 1
      CORE_RPC_HOST: bitcoin
      CORE_RPC_PORT: 18443
      CORE_RPC_USERNAME: root
      CORE_RPC_PASSWORD: password
      ELECTRUM_HOST: electrs
      ELECTRUM_PORT: 50001
      DATABASE_HOST: mariadb
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    volumes:
      - mempool_mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: password

volumes:
  node_blockchain_data:
  peer_blockchain_data:
  electrum_server_data:
  mempool_mariadb_data: