version: '3.7'

services:

  bitcoin:
    container_name: bitcoin
    build: 
      target: bitcoin
      context: .docker/services/bitcoin
    volumes:
      - node_blockchain_data:/var/lib/bitcoind
    ports:
     - 18444:18444
     - 18443:18443
    environment:
      BITCOIN_RPC_SERVER_ENABLED: 1
      BITCOIN_RPC_AUTH_CREDENTIALS: "bitcoin:99ab01ce75f87d87f9639645d24a1443$$9ef4d35ea95682a25dd8f41663bf53f5ede888ce09255328c7f2fdb129210961"
      BITCOIN_ALLOW_RPC_ADDRESS: 0.0.0.0/0
      BITCOIN_TXINDEX_ENABLED: 1
      BITCOIN_REGTEST_CHAIN_ENABLED: 1
      BITCOIN_REGTEST_RPC_BIND_ADDRESS: 0.0.0.0
      
  peer:
    container_name: bitcoin-peer
    build: 
      target: bitcoin-peer
      context: .docker/services/bitcoin
    volumes:
      - peer_blockchain_data:/var/lib/bitcoind
    ports:
     - 18445:18444
    environment:
      BITCOIN_REGTEST_ENABLED: 1
      BITCOIN_REGTEST_PEER: bitcoin

  electrs:
    container_name: electrs
    build: 
      context: .docker/services/electrs
    volumes:
      - electrum_server_data:/var/lib/electrs
    ports:
      - 50001:50001
    depends_on:
      - bitcoin
    environment:
      ELECTRS_BITCOIN_HOST: bitcoin
      ELECTRS_BITCOIN_CHAIN: regtest
      ELECTRS_BITCOIN_P2P_PORT: 18444
      ELECTRS_BITCOIN_RPC_PORT: 18443
      ELECTRS_BITCOIN_RPC_USERNAME: bitcoin
      ELECTRS_BITCOIN_RPC_PASSWORD: bitcoin
      ELECTRS_ELECTRUM_RPC_ADDRESS: 0.0.0.0
      ELECTRS_ELECTRUM_RPC_PORT: 50001

  mempool:
    container_name: mempool
    build: 
      context: .docker/services/mempool
    ports:
      - 3001:80
      - 3002:8999
    depends_on:
      - bitcoin
      - electrs
      - mariadb
    environment:
      MEMPOOL_BACKEND: electrum
      MEMPOOL_INITIAL_BLOCKS_AMOUNT: 1
      MEMPOOL_BITCOIN_CHAIN: regtest
      MEMPOOL_BITCOIN_HOST: bitcoin
      MEMPOOL_BITCOIN_RPC_PORT: 18443
      MEMPOOL_BITCOIN_RPC_USERNAME: bitcoin
      MEMPOOL_BITCOIN_RPC_PASSWORD: bitcoin
      MEMPOOL_ELECTRUM_HOST: electrs
      MEMPOOL_ELECTRUM_PORT: 50001
      MEMPOOL_DATABASE_HOST: mariadb
      MEMPOOL_DATABASE_DATABASE: mempool
      MEMPOOL_DATABASE_USERNAME: mempool
      MEMPOOL_DATABASE_PASSWORD: mempool

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    volumes:
      - mempool_mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: password

volumes:
  node_blockchain_data:
  peer_blockchain_data:
  electrum_server_data:
  mempool_mariadb_data: